---
title: "MUSA8010ModelBuild"
author: "Trevor Kapuvari"
date: "2024-01-30"
output: html_document
---
# Introduction
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(RSocrata)
library(viridis)
library(spatstat)
library(raster)
library(spdep)
library(FNN)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(tidycensus)
library(classInt)
library(RCurl)
library(httr)
library(osmdata)
library(terra)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

st_c    <- st_coordinates
st_coid <- st_centroid

palette6 <- c("#264653","#2a9d8f",'#8AB17D',"#e9c46a",'#f4a261',"#e76f51")
palette5 <- c("#264653","#2a9d8f","#e9c46a",'#f4a261',"#e76f51")
palette4 <- c("#264653","#2a9d8f","#e9c46a","#e76f51")
palette2 <- c("#264653","#2a9d8f")
```

```{r function build}
countfishnet <- function(fishnet,dataset){
  net <- 
  dplyr::select(dataset) %>% 
  mutate(count = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(count = replace_na(count, 0),
         uniqueID = 1:n(),
         cvID = sample(round(nrow(fishnet) / 24), 
                       size=nrow(fishnet), replace = TRUE))
  return(net)
}

knnfishnet <- function(fishnet,dataset,knum){
  vars_net <- dataset%>%
    st_join(fishnet, join=st_within) %>%
    st_drop_geometry() %>%
    group_by(uniqueID,osm_id) %>%
    summarize(count = n()) %>%
    left_join(fishnet, ., by = "uniqueID") %>%
    spread(osm_id, count, fill=0) %>%
    dplyr::select(-`<NA>`) %>%
    ungroup()
  vars_net <- vars_net %>%
    mutate(item.nn = nn_function(st_c(st_coid(vars_net)), 
                                           st_c(dataset),
                                           k = knum))
  return(vars_net)
}

visual <- function(net_one,point_one,variable_name){
grid.arrange(
  ggplot() +
  geom_sf(data = net_one, aes(fill = count), color = NA) +
  scale_fill_viridis() +
  labs(title = paste(variable_name,"count for the fishnet")) +
  mapTheme(),
  ggplot() + 
  geom_sf(data = chen_bdry) +
  geom_sf(data = point_one, colour="red", size=0.2, show.legend = "point") +
  labs(title= paste(variable_name,", Chennai")) +
  mapTheme(title_size = 14),
  nrow = 1
)
}
```


```{r DEM attempt }

Panama = raster("C:/Users/Owner/Downloads/dem30plus_acp.tif")

plot(Panama)
```

  