---
title: "function_uo"
author: "Tianxiao"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("remotes")
#remotes::install_github("IREA-CNR-MI/sprawl")
#install.packages("tidygraph")
library(tidyverse)
library(sf)
library(RSocrata)
library(viridis)
library(spatstat)
library(raster)
library(spdep)
library(FNN)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(tidycensus)
library(classInt)
library(RCurl)
library(httr)
library(osmdata)
library(randomForest)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
#source('https://github.com/TrevorKap/MUSA810-Marine-Pollution/raw/main/function_UO.R')
st_c    <- st_coordinates
st_coid <- st_centroid
```

```{r}
# load litter data
litter <- read.csv('https://raw.githubusercontent.com/TrevorKap/MUSA810-Marine-Pollution/main/Data/mdt-dataMumbai.csv')

# data filter and projection transformation
litter_p <- litter%>%
  filter(master_material == 'PLASTIC')%>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant")%>%
  st_transform('EPSG:32643')
litter_p <- subset(litter_p, select = -c(event_name, project_name))

# load boundary data
## ATTENTION! this part should be the boundry of YOUR CITY
mumb_bdry <- st_read('https://github.com/TrevorKap/MUSA810-Marine-Pollution/raw/main/Data/Mumbai2.kml')
mumb_bdry <- st_set_crs(mumb_bdry, 4326)%>%
  st_transform('EPSG:32643')

# create fishnet of city boundary
fishnet <- 
  st_make_grid(mumb_bdry,
               cellsize = 500, 
               square = TRUE) %>%
  .[mumb_bdry] %>%            
  st_sf() %>%
  mutate(uniqueID = 1:n())

# create fishnet(fn) variable of litter count
litter_net <- countfishnet(fishnet, litter_p)

```

## raster data
```{r}
# load raster data
## ATTENTION! you can download the data from facebook population link to your local place first
## AND, based on the lat & lon to choose the image you need, and the geometry info is in the name of file
img <- raster("/Users/mr.smile/Desktop/UPENN/Spring24/CPLN790/data/population_ind_pak_general/population_10_lon_80_general-v1.5.tif")

# p.s. this part is still the chennai boundary, why i load another one is the original one have incorrect z-dimention and can not be used as mask. 
temp_bd <- st_read('/Users/mr.smile/Desktop/UPENN/Spring24/CPLN790/data/archive (1)/cma_layer.shp')

tifCropped <- crop(img, extent(temp_bd)) # extract raster based on boundary
tifClipped <- mask(tifCropped, temp_bd) # clip the raster based on boundary
polys1 = rasterToPolygons(tifClipped) # convert raster to polygon (it will take some time, it's OK)
sf_object <- st_as_sf(polys1) 
temp <- as.data.frame(sf_object) # convert to sf dataframe
temp_sf <- st_as_sf(temp)
df_points <- st_centroid(temp_sf) # convert to point geometry
```

```{r}
# convert projection
df_points <- df_points%>%
  st_transform('EPSG:32643')
joined_data <- st_join(fishnet, df_points) # merge fishnet and point dataset

# get the average pop of each fishnet cell 
avg_pop <- joined_data %>%
  group_by(uniqueID) %>%
  summarise(avg_pop = mean(Population.Count, na.rm = TRUE))

# data clean
avg_pop[is.na(avg_pop)] <- 0

# get the total pop of each fishnet cell 
sum_pop <- joined_data %>%
  group_by(uniqueID) %>%
  summarise(sum_pop = sum(Population.Count, na.rm = TRUE))
```

```{r}
# pop thing visualize
grid.arrange(
ggplot() +
      geom_sf(data = avg_pop, aes(fill = avg_pop), color = NA) +
      scale_fill_viridis() +
      labs(title = 'Average Pop for the fishnet') +
      mapTheme(),
ggplot() + 
      geom_sf(data = sum_pop, aes(fill = sum_pop), color = NA) +
      scale_fill_viridis() +
      labs(title = 'Total Pop for the fishnet') +
      mapTheme(),
nrow=1)
```

## osm data
```{r}
# reference: https://wiki.openstreetmap.org/wiki/Map_features#Entertainment,_Arts_&_Culture
amenity_wm <- c('waste_basket','waste_disposal','waste_transfer_station','recycling') # done
water<- c('canal','drain','ditch') # done 
leisure <- c('park')
landuse <- c('commercial','residential','retail','industrial') # done 
highway <- c('motorway','trunk','primary','secondary','tertiary','unclassified','residential') # done
act <- c('maxspeed') 
amenity_food <- c('restaurant','pub','bar') # done
building <- ('apartments,')

## ATTENTION! if this part not work, it's totally fine, you can just grab the bbox data in google map
india <- getbb(place_name = "india", format_out = "polygon") # not used 
bb_df <- getbb(place_name = "mumbai india", format_out = "data.frame") # get chennai boundary
bdry <- bb_df$boundingbox # extract the geoemtry part
bdry
mumb_bd <- c(72.947085, 19.180209, 72.7915568, 18.8939566) # just a record


```

```{r get point_nn_fishnet}
water_point <- point_data(mumb_bd, 'water',c('canal','drain','ditch'),'water') # grab osm point data (the detail input variable just check the 'https://raw.githubusercontent.com/TrevorKap/MUSA810-Marine-Pollution/main/function_UO.R' and I have write the input require)
water_net <- countfishnet(fishnet,water_point) # create fn variable of litter count
water_nn_net <- knnfishnet(fishnet,water_point,3) # create fn knn variable 

waste_point <- point_data(mumb_bd, 'amenity',c('waste_basket','waste_disposal','waste_transfer_station','recycling'),'waste')
waste_net <- countfishnet(fishnet,waste_point)
waste_nn_net <- knnfishnet(fishnet,waste_point,3)

rstrt_point <- point_data(mumb_bd, 'amenity',c('restaurant','pub','bar'),'restaurant')
rstrt_net <- countfishnet(fishnet,rstrt_point)
rstrt_nn_net <- knnfishnet(fishnet,rstrt_point,3)

road_point <- point_data(mumb_bd, 'highway','residential','road')
road_net <- countfishnet(fishnet,road_point)
road_nn_net <- knnfishnet(fishnet,road_point,3)

indstr_point <- point_data(mumb_bd, 'landuse','industrial','industrial')
indstr_net <- countfishnet(fishnet,indstr_point)
indstr_nn_net <- knnfishnet(fishnet,indstr_point,3)

rsdnt_point <- point_data(mumb_bd, 'landuse','residential','residential')
rsdnt_net <- countfishnet(fishnet,rsdnt_point)
rsdnt_nn_net <- knnfishnet(fishnet,rsdnt_point,3)

rtl_point <- point_data(mumb_bd, 'landuse','retail','retail')
rtl_net <- countfishnet(fishnet,rtl_point)
rtl_nn_net <- knnfishnet(fishnet,rtl_point,3)
```

```{r}
print(chisq.test(water_net$count,litter_net$count)) # chi-square test 
print(chisq.test(rstrt_net$count,litter_net$count))
print(chisq.test(road_net$count,litter_net$count))
print(chisq.test(waste_net$count,litter_net$count))

print(chisq.test(indstr_net$count,litter_net$count))
print(chisq.test(rsdnt_net$count,litter_net$count))
print(chisq.test(rtl_net$count,litter_net$count))
```

```{r visualize count net}
visual_count_net(water_net,water_point,mumb_bdry,'water') # visualize the point and fn count data
visual_count_net(waste_net,waste_point,mumb_bdry,'waste')
visual_count_net(rstrt_net,rstrt_point,mumb_bdry,'restaurant')
visual_count_net(road_net,road_point,mumb_bdry,'road')
visual_count_net(indstr_net,indstr_point,mumb_bdry,'Industrial Land Use')
visual_count_net(rsdnt_net,rsdnt_point,mumb_bdry,'Residential Land Use')
 visual_count_net(rtl_net,rtl_point,mumb_bdry,'retail Land Use')

nn_visual(water_nn_net,'water') # visualize the knn variable data
nn_visual(waste_nn_net,'waste')
nn_visual(rstrt_nn_net,'restaurant')
nn_visual(road_nn_net,'road')
nn_visual(rtl_nn_net,'retail Land Use')
nn_visual(indstr_nn_net,'Residential Land Use')
nn_visual(indstr_nn_net,'Industrial Land Use')
```

```{r combine the final dataset}
# join all variable to a total dataset
## ATTENTION: just check the column name frequently, it shoulb be some column with same name needed to be rename
## current don't have zoning, remember to add it
final_net <-
  left_join(litter_net, st_drop_geometry(water_nn_net), by="uniqueID")

final_net <-
  left_join(final_net, st_drop_geometry(rstrt_nn_net), by="uniqueID")

final_net <-
  left_join(final_net, st_drop_geometry(road_nn_net), by="uniqueID")

final_net <- final_net%>%
  rename(watr_nn = item.nn.x,
         restaurant_nn = item.nn.y,
         road_nn = item.nn)

final_net <- 
  left_join(final_net,st_drop_geometry(avg_pop), by="uniqueID")

final_net <- 
  left_join(final_net,st_drop_geometry(sum_pop), by="uniqueID")
```

```{r local moran's I analysis}
final_net.nb <- poly2nb(as_Spatial(final_net), queen=TRUE) 

final_net.weights <- nb2listw(final_net.nb, style="W", zero.policy=TRUE) # get local moran spatial weight

# get the locan moral analysis of POI data
local_morans_rst <- localmoran(final_net$restaurant, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
local_morans_road <- localmoran(final_net$road, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
local_morans_wtr <- localmoran(final_net$water, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
```

```{r}
local_morans_sp <- localmoran(final_net$sum_pop, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
lc_mr_visual(local_morans_sp,final_net,'sum_pop')

local_morans_ap <- localmoran(final_net$avg_pop, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
lc_mr_visual(local_morans_ap,final_net,'avg_pop')
```

```{r}
# attention!
# the legends here shoud be the same as label set when create the count fishnet
# visualize the local moran result
lc_mr_visual(local_morans_wtr,final_net,'water')
lc_mr_visual(local_morans_rst,final_net,'restaurant')
lc_mr_visual(local_morans_road,final_net,'road')
```

```{r add lm sig to dataset}
final_net <- lm_col(final_net,local_morans_wtr) # combine the local moran analysis significant point knn into final dataset
final_net <- final_net%>% rename(wtr_sig = col_name, wtr_sig_dis = col_name_dis) # rename the name of column

final_net <- lm_col(final_net,local_morans_road)
final_net <- final_net%>% rename(road_sig = col_name, road_sig_dis = col_name_dis)

final_net <- lm_col(final_net,local_morans_rst)
final_net <- final_net%>% rename(rst_sig = col_name, rst_sig_dis = col_name_dis)
```

```{r}
# visualzie the signifcant point knn of variable
grid.arrange(
ggplot() +
      geom_sf(data = final_net, aes(fill=rst_sig_dis), colour=NA) +
      scale_fill_viridis(name="NN Distance") +
      labs(title="Restaurant NN Distance") +
      mapTheme(),
ggplot() +
      geom_sf(data = final_net, aes(fill=road_sig_dis), colour=NA) +
      scale_fill_viridis(name="NN Distance") +
      labs(title="Road NN Distance") +
      mapTheme(),
ggplot() +
      geom_sf(data = final_net, aes(fill=wtr_sig_dis), colour=NA) +
      scale_fill_viridis(name="NN Distance") +
      labs(title="Water NN Distance") +
      mapTheme(),
nrow = 1)
```

```{r}
reg.ss.vars <- c("restaurant_nn", "rst_sig_dis","road_nn", "road_sig_dis","watr_nn", "wtr_sig_dis") # the independent variables included

## RUN REGRESSIONS
reg.ss.spatialCV <- crossValidate(
  dataset = final_net,
  id = "uniqueID",                           
  dependentVariable = "count", # this count is the litter count 
  indVariables = reg.ss.vars) %>%
    dplyr::select(uniqueID, count, Prediction, geometry)
```

```{r}
# this chunk don't need to be run
error_by_reg_and_fold <- 
  reg.ss.spatialCV %>%
    group_by(uniqueID) %>% 
    summarize(Mean_Error = mean(Prediction - count, na.rm = T),
              MAE = mean(abs(Mean_Error), na.rm = T),
              SD_MAE = mean(abs(Mean_Error), na.rm = T)) %>%
  ungroup()

error_by_reg_and_fold %>% 
  arrange(desc(MAE))

error_by_reg_and_fold %>% 
  arrange(MAE)

error_by_reg_and_fold %>% filter(MAE <= 10)%>%
  ggplot(aes(MAE)) + 
    geom_histogram(bins = 100, colour="black", fill = "#FDE725FF") +
  scale_x_continuous(breaks = seq(0, 11, by = 1)) + 
    labs(title="Distribution of MAE", subtitle = "LOGO-CV",
         x="Mean Absolute Error", y="Count") 
```

```{r}
risk_v(reg.ss.spatialCV,litter_p,'kmeans') # visualize the MSE of prediction
```

```